### ISSUE TITLE
Tensor regression layer version disable in script mnist.py

### ISSUE THREAD

**Issue by ccaiafa** [Vixaer/LowRankTRN#1]
Hi,
Thanks for sharing the code of your nice new paper. 
I noticed the script mnist.py run the baseline version with fully connected layer.
I would like to run the Tucker Tensor Regression Layer version of this script but I am not sure which lines should be uncommented. I tried uncommenting lines 96-102 but the code doesnt work.
Could you please provide a clean version of the script using the Tucker Tensor Regression Layer?
Thank you very much!!!
Cesar

**Comment by xwcao** [comment]
Hi Cesar, Thank you for the comment on the code.
I cleaned the mnist.py code and I hope it is readable now.

The lines from 84 to 86 of the new mnist.py file correspond to the three types of regression layer; ttrl **(Tensor train regression layer)** , trl **(Tucker Regression Layer)** and cprl **(CP regression layer)**.

TT
```
out = ttrl(tf.nn.relu(h_pool2), rank, 10)
```

CP
```
out = cprl(tf.nn.relu(h_pool2), rank, 10)
```

Tucker
```
out = trl(tf.nn.relu(h_pool2), rank, 10)
```

Sorry for the dirty code and please let me know if you have any further trouble running mnist.py!

**Comment by ccaiafa** [comment]
Hi Jstn,
Thank you very much for the new code. I really appreciated it.
I am getting the following error when I run the new mnist.py script:

  File "/Users/CesarMB13/PycharmProjects/TensorRegression/LowRankTRN/util.py", line 12, in unfold
    return tf.reshape(tensor = tf.transpose(tensor, [mode] + lst[:mode] + lst[mode+1:]), shape = [tensor.get_shape().as_list()[mode],-1])
TypeError: can only concatenate list (not "range") to list
Process finished with exit code 1

It seems that there is a problem with the unfold function in utils.

Do you know what is the problem now?
Thanks again!
Cesar

**Comment by xwcao** [comment]
Hi Cesar,
The problem here I think is the version of Python.

I use python 2.7 and the **range** function returns list whereas in python 3.x **range** returns an object "range".

**Python 3.x**
```python
>>> range(5)
range(0, 5)
>>> list(range(5)) 
[0, 1, 2, 3, 4]
```

**Python 2.7** (the version that I use for LowRankTRN)
```python
>>> range(0,5)
[0, 1, 2, 3, 4]
```

To fix (compatible to Python 3.x), one can wrap the range function with `list()`. For example, change `range(x)` to `list(range(x))` for python 3.x! 

I hope this solves your problem!

**Comment by ccaiafa** [comment]
Thanks Jstn! I am running it with Python 2.7 and it seems to work OK. I am closing the issue

**Comment by keyxiang** [comment]
hi , I seem to have come across a dimensional mismatch when I run the new fmnist.py script:
ValueError: Shape error. 10(matrix's 2nd dimension) is not as same as 1 (dimension of the tensor)
Do you know what is the problem now?
Thanks a lot!
